# Generated by Django 2.0.5 on 2018-09-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='exam',
            name='Exam',
            field=models.FileField(upload_to=''),
        ),
    ]
