# Generated by Django 2.0.5 on 2018-12-11 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0014_auto_20181210_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_files',
            name='user',
            field=models.OneToOneField(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
