version: "3.5"

services:
  django:
    image: brunnelu/django:0.0.5
    build: $PWD/.
    #command: pip install django-multiselectfield
    volumes:
      - $PWD/static:/var/www/static
      - $PWD/code:/usr/django/app
      - $PWD/gunicorn.conf:/etc/gunicorn/gunicorn.conf
    ports:
      - "8000:8000"
    environment:
      DJANGO_APP: 'webapp'
      DJANGO_MANAGEMENT_ON_START: 'migrate --noinput;collectstatic --noinput'
      #SECRET_KEY: 'Kou*J@66,3-k7JMER@s/gx(Yy!g8M%wyqDcKu8'
      DJANGO_DEBUG: 'True'
    
  nginx:
    image: nginx:latest
    volumes:
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/nginx/logs:/var/log/nginx
      - $PWD/static:/var/www/static
    ports:
      - "80:80"