version: "3.5"

services:
  app:
    image: brunnelu/django:0.0.7
    build: .
    restart: always
    volumes:
      - $PWD/static:/var/www/static
      - $PWD/media:/var/www/media
      - $PWD/app:/app
    ports:
      - "8000:8000"
    environment:
      #DJANGO_APP: 'webapp'
      #DJANGO_MANAGEMENT_ON_START: 'migrate --noinput;collectstatic --noinput'
      SECRET_KEY: 'Kou*J@66,3-k7JMER@s/gx(Yy!g8M%wyqDcKu8ER@s/gx(Yy!g8M%wyqDcKER@s/gx(Yy!g8M%wyqDcK'
      #DJANGO_DEBUG: 'True'
    command:
      "bash start.sh"
      
  nginx:
    image: nginx:latest
    volumes:
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/nginx/logs:/var/log/nginx
      - $PWD/static:/var/www/static
      - $PWD/media:/var/www/media
    ports:
      - "80:80"
