# Generated by Django 2.0.5 on 2018-11-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_auto_20181116_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_test',
            name='relevance',
            field=models.IntegerField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')]),
        ),
        migrations.AlterField(
            model_name='choice_test',
            name='status',
            field=models.IntegerField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')]),
        ),
    ]
