# Generated by Django 2.0.5 on 2018-11-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20181117_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_test',
            name='status',
            field=models.IntegerField(choices=[(1, 'GREEN'), (2, 'BLUE'), (3, 'RED'), (4, 'ORANGE'), (5, 'BLACK')]),
        ),
    ]
