# Generated by Django 2.0.5 on 2018-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0007_auto_20181117_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Jahrgang', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('Fach', models.IntegerField(choices=[(1, 'Français'), (2, 'Deutsch'), (3, 'English'), (4, 'Physik'), (5, 'Chemie'), (6, 'Biologie'), (7, 'Ergänzungsfach'), (8, 'Wahlkurs'), (9, 'Geschichte')])),
                ('Schwerpunkt', models.IntegerField(choices=[(1, 'JA'), (2, 'NEIN')])),
                ('Lehrperson', models.IntegerField(choices=[(1, 'Weber'), (2, 'Gremaud'), (3, 'Häne'), (4, 'Formenti')])),
            ],
        ),
    ]
