# Generated by Django 2.0.5 on 2018-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0009_auto_20181119_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_files',
            name='Exam',
            field=models.FileField(default='fileupload/webapp/media/textfile.txt', upload_to=''),
        ),
    ]
