# Generated by Django 2.0.5 on 2018-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0011_auto_20181120_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_files',
            name='Schwerpunkt',
            field=models.IntegerField(blank=True, choices=[(1, 'JA'), (2, 'NEIN')]),
        ),
    ]
