# Generated by Django 2.0.5 on 2018-12-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0012_auto_20181120_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choice_test',
        ),
        migrations.DeleteModel(
            name='exam',
        ),
    ]
