# Generated by Django 2.0.5 on 2018-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0013_auto_20181208_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_files',
            name='Fach',
            field=models.IntegerField(choices=[(1, 'Anwendungen der Mathematik'), (2, 'Bildnerisches Gestalten'), (3, 'Biologie'), (4, 'Chemie'), (5, 'Englisch'), (6, 'Ergänzungsfach'), (7, 'Französisch'), (8, 'Geschichte'), (9, 'Italienisch'), (10, 'Latein'), (11, 'Mathematik'), (12, 'Physik'), (13, 'Russisch'), (14, 'Spanisch'), (15, 'Wirtschaft und Recht')]),
        ),
        migrations.AlterField(
            model_name='test_files',
            name='Schwerpunkt',
            field=models.IntegerField(choices=[(1, 'JA'), (2, 'NEIN')]),
        ),
    ]
