# Generated by Django 2.0.5 on 2018-12-11 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0015_test_files_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_files',
            name='user',
        ),
        migrations.AddField(
            model_name='test_files',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
