# Generated by Django 2.0.5 on 2018-12-11 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0018_auto_20181211_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_files',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
