# Generated by Django 2.0.5 on 2018-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20180914_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1)),
                ('relevance', models.IntegerField(choices=[(1, 'Unread'), (2, 'Read')], default=1)),
            ],
        ),
    ]
